version: "3.7"
services:

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    restart: always
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - backend_static:/var/www/html/static:ro
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend:latest
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - backend_static:/app/static
    networks:
      - app_network

volumes:
  caddy_data:
  caddy_config:
  backend_static:
  
networks:
  app_network:
    driver: bridge