name: Build Web UI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
    copy_files:
      name: Copy files
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Copy Caddyfile to remote host
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_SSHKEY }}
            port: ${{ secrets.SERVER_PORT }}
            source: "Caddyfile, docker-compose.yml"
            target: ${{ secrets.PATH_APP }}
            # strip_components: 1

    build:
      name: Build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install bun
          uses: oven-sh/setup-bun@v2

        - name: Build frontend
          run: bun run build

        - name: Archive files
          run: tar -czf dist.tar.gz dist

    deploy:
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      needs: ['build']

      steps:
        - name: Deploy to server
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd ${{ secrets.PATH_APP }}
              tar -xzf dist.tar.gz -C .
              # docker-compose up -d